### ISSUE TITLE
Error running sample data

### ISSUE THREAD

**Issue by dsfigueroa** [wmalab/DiffGR#1]
Hi, 
when I run the sample data,

dat1 <- readRDS("path/dat.GM12878.chr10.rds")
dat2 <- readRDS("path/dat.K562.chr10.rds")
result <- DiffGR(dat1,dat2,smooth.size=5,res=50000)

 I get this error: **Error: KR normalization for dat1 did not converge.**

**Comment by lhlruc** [comment]
> Hi,
> when I run the sample data,
> 
> dat1 <- readRDS("path/dat.GM12878.chr10.rds")
> dat2 <- readRDS("path/dat.K562.chr10.rds")
> result <- DiffGR(dat1,dat2,smooth.size=5,res=50000)
> 
> I get this error: **Error: KR normalization for dat1 did not converge.**

Sorry, I made some adjustments on my code and accidentally uploaded
the unfinished version on Github. I just updated the newest version,
please check.
