### ISSUE TITLE
hicrep

### ISSUE THREAD

**Issue by srcoulombe** [wmalab/DiffGR#3]
Here's a summary of the issues encountered that are related to the hicrep package. 

As explained in the README, DiffGR after first installing HiCcompare, hicrep，HiCseg and R.utils. I then tried to run the sample code provided:

```
dat1 <- readRDS("path/dat.GM12878.chr10.rds")
dat2 <- readRDS("path/dat.K562.chr10.rds")
result <- DiffGR(dat1,dat2,smooth.size=5,res=50000)
```
but the following issues came up

1. smoothMat

```
Error in smoothMat(dat1, smooth.size) :
  could not find function "smoothMat"
```
As explained in [this issue](https://github.com/wmalab/DiffGR/issues/2), the smoothMat function was [removed from Tao Yang's repo in 2017](https://github.com/TaoYang-dev/hicrep/search?q=smoothMat&type=commits). It is not included in hicrep version 1.12.2. The function is still included in the [Qunhua Li lab's repo](https://github.com/qunhualilab/hicrep), but it still isn't included when you install their version of the package (1.11.0). The ```fast.mean.filter``` (see [here](https://github.com/TaoYang-dev/hicrep/blob/master/R/fast.mean.filter.R) or [here](https://github.com/qunhualilab/hicrep/blob/master/R/fast.mean.filter.R)) seems to have taken its place (my best guess is that it is more readable and faster).

*suggestion*: replace calls to ```smoothMat``` with calls to ```fast.mean.filter```.

2. get.scc

```
Error in get.scc(dat.comb, 1, max.distance) :
  argument "h" is missing, with no default
```

```get.scc``` used to have three positional arguments in [2017](https://github.com/TaoYang-dev/hicrep/commit/36e0b108a6906c9b2d6b3c2dfbab8e1c4089ad08#diff-6e284a9ec139528eaef15146d893725d145b5a797e910488242d1b8ceb50dad4), but that [changed with version 1.0.1](https://github.com/TaoYang-dev/hicrep/commit/f6800a3303bfb9d4b4b7900a35e53702cc747251#diff-6e284a9ec139528eaef15146d893725d145b5a797e910488242d1b8ceb50dad4). It now includes six arguments, and operates on a pair of matrices ([see here](https://github.com/TaoYang-dev/hicrep/blob/master/R/get.scc.R)).

*suggestion*: right now, the calls to ```get.scc``` in the function ```scc``` always crash due to the parameter mismatch. Re-writing ```scc``` to make it compatible with hicrep would be ideal. Otherwise, the old version of ```get.scc``` could be included in DiffGR.R. The former is better than the latter, as a justification of why the old version of ```get.scc``` (without the updated parameters) is used instead of the most up-to-date version.

**Comment by srcoulombe** [comment]
If any other issues related to hicrep are found, it would be a good idea to document them all here.

**Comment by lhlruc** [comment]
Thanks for the notification! Due to the issue in current hicrep package, I have already copied the codes of partial functions in hicrep previous version 1.8.0 to maintain the operation of DiffGR function.

**Comment by lhlruc** [comment]
The description of relative hicrep functions in previous version 1.8.0 can be found in https://bioconductor.statistik.tu-dortmund.de/packages/3.9/bioc/manuals/hicrep/man/hicrep.pdf
