### ISSUE TITLE
Hard-coded dependence on HiCSeg

### ISSUE THREAD

**Issue by srcoulombe** [wmalab/DiffGR#4]
The arxiv paper explains that 'one can exchange HiCseg with another TAD caller in this step', but the current version of DiffGR hardcodes HiCseg as the TAD-caller:
```
  tad <- HiCseg_linkC_R(nrow(dat1),round(nrow(dat1)/3),"P",dat1,"D")
  tad1 <- tad$t_hat[tad$t_hat!=0]
  tad <- HiCseg_linkC_R(nrow(dat2),round(nrow(dat2)/3),"P",dat2,"D")
  tad2 <- tad$t_hat[tad$t_hat!=0]
```

I think it would be feasible to simply nest those four lines in an if-block and have ```tad1``` and ```tad2``` as optional arguments to the ```DiffGR``` function. For instance:

```
DiffGR<- function(dat1,dat2,res,smooth.size,N.perm=2000,cutoff.default=TRUE,speedup.option=TRUE,alpha=0.05,tad1=NULL,tad2=NULL){
  ... 
  if is.null(tad1) {
    tad <- HiCseg_linkC_R(nrow(dat1),round(nrow(dat1)/3),"P",dat1,"D")
    tad1 <- tad$t_hat[tad$t_hat!=0]
  }
  if is.null(tad2) {
    tad <- HiCseg_linkC_R(nrow(dat2),round(nrow(dat2)/3),"P",dat2,"D")
    tad2 <- tad$t_hat[tad$t_hat!=0]
  }
}
```

I'm willing to open a PR and work on this, but I'm not sure what assumptions DiffGR makes of the values in ```tad1``` and ```tad2```; [HiCSeg's documentation](https://cran.r-project.org/web/packages/HiCseg/vignettes/HiCseg.pdf) shows that ```tad1``` and ```tad2``` are vectors whose values correspond to TAD boundaries, but does DiffGR allow for overlapping and hierarchical TAD boundaries?

**Comment by lhlruc** [comment]
Thanks for your advice !  I will take a look and update my code later to fulfill the need of inputting TAD boundaries from other TAD detection method. 
In DiffGR, we required the detected TADs with non-overlapping and continuous properties to satisfy the genomic region classification. Thus, besides HiCseg, Insulation score can also be utilized for TAD calling.

**Comment by srcoulombe** [comment]
Sorry to re-open this issue, I just wanted to clarify whether you are open to open-source contributors or if you aren't accepting PRs at the moment.

**Comment by lhlruc** [comment]
Sorry, our manuscript is planned to submit soon and we will open to open-source contributors once it is accepted.
